### PR TITLE
ESX Weight

### PR DESCRIPTION
**Pull request by yagizher**
Well, idk if it works. I couldnt find the carry item limit so i wasnt able to change it, if you do know i hope you change it.

### CODE REVIEW

**Comment by rex2630** [comment]
What about other locales?

**Comment by yagizher** [comment]
Oh, fixing.

**Comment by yagizher** [comment]
Fixed br_esx_jobs too, was missing limit. I added weight instead.

**Comment by BrakingESX247** [comment]
The changes have already been made, thank you anyways.

**Pull request closed without merging**
